const fs = require("fs");

/**the default folder where the readme files are created */
const outputFolder = "./output/";
const templateFile = "template.md";

/**
 * Method generates the readme markdown for a given user and project data
 * @param {Object} user the user data from GitHub
 * @param {Object} project the project data entered by the user
 * @returns {String} the generated readme file markdown
 */
function generateMarkdown(user, project) {
  const readmeTemplate = fs.readFileSync(templateFile, "UTF8");
  return applyTemplate(readmeTemplate, user, project);
}

/**
 * Method renders the template and generates the content of the readme file
 * @param {String} readmeTemplate the raw template to be used to generate the readme
 * @param {Object} user the user data from GitHub to be used in the template
 * @param {Object} project the project data to be used in the template
 * @returns {String} the readme file content generated by the template
 */
function applyTemplate(readmeTemplate, user, project) {
  return eval('`' + readmeTemplate + '`');
}

/**
 * Saves the markdown data to a new readme file and returns the location of the file
 * @param {*} markdown the readme file markdown data
 * @returns {String} the location of the newly generated readme file
 */
function createReadme(markdown) {
  // Create output folder if it doesn't exist
  if (!fs.existsSync(outputFolder)) {
    fs.mkdirSync(outputFolder);
  }
  // Generate unique filename and save to file
  let timeStamp = Date.now();
  let filePath = `${outputFolder}README_${timeStamp}.md`;
  fs.writeFileSync(filePath, markdown);
  return filePath;
}

/**
 * Method generates a new readme file for a given user and project data 
 * and returns the location of the newly generated file
 * @param {Object} user the user data from GitHub
 * @param {Object} project the project data entered by the user
 * @returns {String} the location of the newly generated file
 */
function generate(user, project) {
  let markdown = generateMarkdown(user, project);
  return createReadme(markdown);
}

module.exports = {
  generate: generate
};